const continents = {
  africa: {
    countries: {
        "Algeria": {code: "DZ"},
        "Angola": {code: "AO"},
        "Benin": {code: "BJ"},
        "Botswana": {code: "BW"},
        "British Indian Ocean Territory": {code: "IO"},
        "Burkina Faso": {code: "BF"},
        "Burundi": {code: "BI"},
        "Cameroon": {code: "CM"},
        "Cape Verde": {code: "CV"},
        "Central African Republic": {code: "CF"},
        "Chad": {code: "TD"},
        "Comoros": {code: "KM"},
        "DR Congo": {code: "CD"},
        "Djibouti": {code: "DJ"},
        "Egypt": {code: "EG"},
        "Equatorial Guinea": {code: "GQ"},
        "Eritrea": {code: "ER"},
        "Ethiopia": {code: "ET"},
        "Gabon": {code: "GA"},
        "Gambia": {code: "GM"},
        "Ghana": {code: "GH"},
        "Guinea": {code: "GN"},
        "Guinea-Bissau": {code: "GW"},
        "Ivory Coast": {code: "CI"},
        "Kenya": {code: "KE"},
        "Lesotho": {code: "LS"},
        "Liberia": {code: "LR"},
        "Libya": {code: "LY"},
        "Madagascar": {code: "MG"},
        "Malawi": {code: "MW"},
        "Mali": {code: "ML"},
        "Mauritania": {code: "MR"},
        "Mauritius": {code: "MU"},
        "Mayotte": {code: "YT"},
        "Morocco": {code: "MA"},
        "Mozambique": {code: "MZ"},
        "Namibia": {code: "NA"},
        "Niger": {code: "NE"},
        "Nigeria": {code: "NG"},
        "Republic of the Congo": {code: "CG"},
        "Rwanda": {code: "RW"},
        "Réunion": {code: "RE"},
        "Saint Helena, Ascension and Tristan da Cunha": {code: "SH"},
        "Senegal": {code: "SN"},
        "Seychelles": {code: "SC"},
        "Sierra Leone": {code: "SL"},
        "Somalia": {code: "SO"},
        "South Africa": {code: "ZA"},
        "South Sudan": {code: "SS"},
        "Sudan": {code: "SD"},
        "Swaziland": {code: "SZ"},
        "São Tomé and Príncipe": {code: "ST"},
        "Tanzania": {code: "TZ"},
        "Togo": {code: "TG"},
        "Tunisia": {code: "TN"},
        "Uganda": {code: "UG"},
        "Western Sahara": {code: "EH"},
        "Zambia": {code: "ZM"},
        "Zimbabwe": {code: "ZW"},
    },
    measuresFetched: false,
  },
  america: {
    countries: {
      "Anguilla": {code: "AI"},
      "Antigua and Barbuda": {code: "AG"},
      "Argentina": {code: "AR"},
      "Aruba": {code: "AW"},
      "Bahamas": {code: "BS"},
      "Barbados": {code: "BB"},
      "Belize": {code: "BZ"},
      "Bermuda": {code: "BM"},
      "Bolivia": {code: "BO"},
      "Bonaire": {code: "BQ"},
      "Brazil": {code: "BR"},
      "British Virgin Islands": {code: "VG"},
      "Canada": {code: "CA"},
      "Cayman Islands": {code: "KY"},
      "Chile": {code: "CL"},
      "Colombia": {code: "CO"},
      "Costa Rica": {code: "CR"},
      "Cuba": {code: "CU"},
      "Curaçao": {code: "CW"},
      "Dominica": {code: "DM"},
      "Dominican Republic": {code: "DO"},
      "Ecuador": {code: "EC"},
      "El Salvador": {code: "SV"},
      "Falkland Islands": {code: "FK"},
      "French Guiana": {code: "GF"},
      "Greenland": {code: "GL"},
      "Grenada": {code: "GD"},
      "Guadeloupe": {code: "GP"},
      "Guatemala": {code: "GT"},
      "Guyana": {code: "GY"},
      "Haiti": {code: "HT"},
      "Honduras": {code: "HN"},
      "Jamaica": {code: "JM"},
      "Martinique": {code: "MQ"},
      "Mexico": {code: "MX"},
      "Montserrat": {code: "MS"},
      "Nicaragua": {code: "NI"},
      "Panama": {code: "PA"},
      "Paraguay": {code: "PY"},
      "Peru": {code: "PE"},
      "Puerto Rico": {code: "PR"},
      "Saint Barthélemy": {code: "BL"},
      "Saint Kitts and Nevis": {code: "KN"},
      "Saint Lucia": {code: "LC"},
      "Saint Martin": {code: "MF"},
      "Saint Pierre and Miquelon": {code: "PM"},
      "Saint Vincent and the Grenadines": {code: "VC"},
      "Sint Maarten": {code: "SX"},
      "South Georgia": {code: "GS"},
      "Suriname": {code: "SR"},
      "Trinidad and Tobago": {code: "TT"},
      "Turks and Caicos Islands": {code: "TC"},
      "United States": {code: "US"},
      "United States Minor Outlying Islands": {code: "UM"},
      "United States Virgin Islands": {code: "VI"},
      "Uruguay": {code: "UY"},
      "Venezuela": {code: "VE"},
    },
    measuresFetched: false,
  },
  asia: {
    countries: {
      "Afghanistan": {code: "AF"},
      "Armenia": {code: "AM"},
      "Azerbaijan": {code: "AZ"},
      "Bahrain": {code: "BH"},
      "Bangladesh": {code: "BD"},
      "Bhutan": {code: "BT"},
      "Brunei": {code: "BN"},
      "Cambodia": {code: "KH"},
      "China": {code: "CN"},
      "Georgia": {code: "GE"},
      "Hong Kong": {code: "HK"},
      "India": {code: "IN"},
      "Indonesia": {code: "ID"},
      "Iran": {code: "IR"},
      "Iraq": {code: "IQ"},
      "Israel": {code: "IL"},
      "Japan": {code: "JP"},
      "Jordan": {code: "JO"},
      "Kazakhstan": {code: "KZ"},
      "Kuwait": {code: "KW"},
      "Kyrgyzstan": {code: "KG"},
      "Laos": {code: "LA"},
      "Lebanon": {code: "LB"},
      "Macau": {code: "MO"},
      "Malaysia": {code: "MY"},
      "Maldives": {code: "MV"},
      "Mongolia": {code: "MN"},
      "Myanmar": {code: "MM"},
      "Nepal": {code: "NP"},
      "North Korea": {code: "KP"},
      "Oman": {code: "OM"},
      "Pakistan": {code: "PK"},
      "Palestine": {code: "PS"},
      "Philippines": {code: "PH"},
      "Qatar": {code: "QA"},
      "Saudi Arabia": {code: "SA"},
      "Singapore": {code: "SG"},
      "South Korea": {code: "KR"},
      "Sri Lanka": {code: "LK"},
      "Syria": {code: "SY"},
      "Taiwan": {code: "TW"},
      "Tajikistan": {code: "TJ"},
      "Thailand": {code: "TH"},
      "Timor-Leste": {code: "TL"},
      "Turkey": {code: "TR"},
      "Turkmenistan": {code: "TM"},
      "United Arab Emirates": {code: "AE"},
      "Uzbekistan": {code: "UZ"},
      "Vietnam": {code: "VN"},
      "Yemen": {code: "YE"},
    },
    measuresFetched: false,
  },
  europe: {
    countries: {
      "Albania": {code: "AL"},
      "Andorra": {code: "AD"},
      "Austria": {code: "AT"},
      "Belarus": {code: "BY"},
      "Belgium": {code: "BE"},
      "Bosnia and Herzegovina": {code: "BA"},
      "Bulgaria": {code: "BG"},
      "Croatia": {code: "HR"},
      "Cyprus": {code: "CY"},
      "Czech Republic": {code: "CZ"},
      "Denmark": {code: "DK"},
      "Estonia": {code: "EE"},
      "Faroe Islands": {code: "FO"},
      "Finland": {code: "FI"},
      "France": {code: "FR"},
      "Germany": {code: "DE"},
      "Gibraltar": {code: "GI"},
      "Greece": {code: "GR"},
      "Guernsey": {code: "GG"},
      "Hungary": {code: "HU"},
      "Iceland": {code: "IS"},
      "Ireland": {code: "IE"},
      "Isle of Man": {code: "IM"},
      "Italy": {code: "IT"},
      "Jersey": {code: "JE"},
      "Latvia": {code: "LV"},
      "Liechtenstein": {code: "LI"},
      "Lithuania": {code: "LT"},
      "Luxembourg": {code: "LU"},
      "Macedonia": {code: "MK"},
      "Malta": {code: "MT"},
      "Moldova": {code: "MD"},
      "Monaco": {code: "MC"},
      "Montenegro": {code: "ME"},
      "Netherlands": {code: "NL"},
      "Norway": {code: "NO"},
      "Poland": {code: "PL"},
      "Portugal": {code: "PT"},
      "Romania": {code: "RO"},
      "Russia": {code: "RU"},
      "San Marino": {code: "SM"},
      "Serbia": {code: "RS"},
      "Slovakia": {code: "SK"},
      "Slovenia": {code: "SI"},
      "Spain": {code: "ES"},
      "Svalbard and Jan Mayen": {code: "SJ"},
      "Sweden": {code: "SE"},
      "Switzerland": {code: "CH"},
      "Ukraine": {code: "UA"},
      "United Kingdom": {code: "GB"},
      "Vatican City": {code: "VA"},
      "Åland Islands": {code: "AX"},
    },
    measuresFetched: false
  },
  world : {
    countries: {
      "Algeria": {code: "DZ"},
        "Angola": {code: "AO"},
        "Benin": {code: "BJ"},
        "Botswana": {code: "BW"},
        "British Indian Ocean Territory": {code: "IO"},
        "Burkina Faso": {code: "BF"},
        "Burundi": {code: "BI"},
        "Cameroon": {code: "CM"},
        "Cape Verde": {code: "CV"},
        "Central African Republic": {code: "CF"},
        "Chad": {code: "TD"},
        "Comoros": {code: "KM"},
        "DR Congo": {code: "CD"},
        "Djibouti": {code: "DJ"},
        "Egypt": {code: "EG"},
        "Equatorial Guinea": {code: "GQ"},
        "Eritrea": {code: "ER"},
        "Ethiopia": {code: "ET"},
        "Gabon": {code: "GA"},
        "Gambia": {code: "GM"},
        "Ghana": {code: "GH"},
        "Guinea": {code: "GN"},
        "Guinea-Bissau": {code: "GW"},
        "Ivory Coast": {code: "CI"},
        "Kenya": {code: "KE"},
        "Lesotho": {code: "LS"},
        "Liberia": {code: "LR"},
        "Libya": {code: "LY"},
        "Madagascar": {code: "MG"},
        "Malawi": {code: "MW"},
        "Mali": {code: "ML"},
        "Mauritania": {code: "MR"},
        "Mauritius": {code: "MU"},
        "Mayotte": {code: "YT"},
        "Morocco": {code: "MA"},
        "Mozambique": {code: "MZ"},
        "Namibia": {code: "NA"},
        "Niger": {code: "NE"},
        "Nigeria": {code: "NG"},
        "Republic of the Congo": {code: "CG"},
        "Rwanda": {code: "RW"},
        "Réunion": {code: "RE"},
        "Saint Helena, Ascension and Tristan da Cunha": {code: "SH"},
        "Senegal": {code: "SN"},
        "Seychelles": {code: "SC"},
        "Sierra Leone": {code: "SL"},
        "Somalia": {code: "SO"},
        "South Africa": {code: "ZA"},
        "South Sudan": {code: "SS"},
        "Sudan": {code: "SD"},
        "Swaziland": {code: "SZ"},
        "São Tomé and Príncipe": {code: "ST"},
        "Tanzania": {code: "TZ"},
        "Togo": {code: "TG"},
        "Tunisia": {code: "TN"},
        "Uganda": {code: "UG"},
        "Western Sahara": {code: "EH"},
        "Zambia": {code: "ZM"},
        "Zimbabwe": {code: "ZW"},
        "Anguilla": {code: "AI"},
      "Antigua and Barbuda": {code: "AG"},
      "Argentina": {code: "AR"},
      "Aruba": {code: "AW"},
      "Bahamas": {code: "BS"},
      "Barbados": {code: "BB"},
      "Belize": {code: "BZ"},
      "Bermuda": {code: "BM"},
      "Bolivia": {code: "BO"},
      "Bonaire": {code: "BQ"},
      "Brazil": {code: "BR"},
      "British Virgin Islands": {code: "VG"},
      "Canada": {code: "CA"},
      "Cayman Islands": {code: "KY"},
      "Chile": {code: "CL"},
      "Colombia": {code: "CO"},
      "Costa Rica": {code: "CR"},
      "Cuba": {code: "CU"},
      "Curaçao": {code: "CW"},
      "Dominica": {code: "DM"},
      "Dominican Republic": {code: "DO"},
      "Ecuador": {code: "EC"},
      "El Salvador": {code: "SV"},
      "Falkland Islands": {code: "FK"},
      "French Guiana": {code: "GF"},
      "Greenland": {code: "GL"},
      "Grenada": {code: "GD"},
      "Guadeloupe": {code: "GP"},
      "Guatemala": {code: "GT"},
      "Guyana": {code: "GY"},
      "Haiti": {code: "HT"},
      "Honduras": {code: "HN"},
      "Jamaica": {code: "JM"},
      "Martinique": {code: "MQ"},
      "Mexico": {code: "MX"},
      "Montserrat": {code: "MS"},
      "Nicaragua": {code: "NI"},
      "Panama": {code: "PA"},
      "Paraguay": {code: "PY"},
      "Peru": {code: "PE"},
      "Puerto Rico": {code: "PR"},
      "Saint Barthélemy": {code: "BL"},
      "Saint Kitts and Nevis": {code: "KN"},
      "Saint Lucia": {code: "LC"},
      "Saint Martin": {code: "MF"},
      "Saint Pierre and Miquelon": {code: "PM"},
      "Saint Vincent and the Grenadines": {code: "VC"},
      "Sint Maarten": {code: "SX"},
      "South Georgia": {code: "GS"},
      "Suriname": {code: "SR"},
      "Trinidad and Tobago": {code: "TT"},
      "Turks and Caicos Islands": {code: "TC"},
      "United States": {code: "US"},
      "United States Minor Outlying Islands": {code: "UM"},
      "United States Virgin Islands": {code: "VI"},
      "Uruguay": {code: "UY"},
      "Venezuela": {code: "VE"},
      "Anguilla": {code: "AI"},
      "Antigua and Barbuda": {code: "AG"},
      "Argentina": {code: "AR"},
      "Aruba": {code: "AW"},
      "Bahamas": {code: "BS"},
      "Barbados": {code: "BB"},
      "Belize": {code: "BZ"},
      "Bermuda": {code: "BM"},
      "Bolivia": {code: "BO"},
      "Bonaire": {code: "BQ"},
      "Brazil": {code: "BR"},
      "British Virgin Islands": {code: "VG"},
      "Canada": {code: "CA"},
      "Cayman Islands": {code: "KY"},
      "Chile": {code: "CL"},
      "Colombia": {code: "CO"},
      "Costa Rica": {code: "CR"},
      "Cuba": {code: "CU"},
      "Curaçao": {code: "CW"},
      "Dominica": {code: "DM"},
      "Dominican Republic": {code: "DO"},
      "Ecuador": {code: "EC"},
      "El Salvador": {code: "SV"},
      "Falkland Islands": {code: "FK"},
      "French Guiana": {code: "GF"},
      "Greenland": {code: "GL"},
      "Grenada": {code: "GD"},
      "Guadeloupe": {code: "GP"},
      "Guatemala": {code: "GT"},
      "Guyana": {code: "GY"},
      "Haiti": {code: "HT"},
      "Honduras": {code: "HN"},
      "Jamaica": {code: "JM"},
      "Martinique": {code: "MQ"},
      "Mexico": {code: "MX"},
      "Montserrat": {code: "MS"},
      "Nicaragua": {code: "NI"},
      "Panama": {code: "PA"},
      "Paraguay": {code: "PY"},
      "Peru": {code: "PE"},
      "Puerto Rico": {code: "PR"},
      "Saint Barthélemy": {code: "BL"},
      "Saint Kitts and Nevis": {code: "KN"},
      "Saint Lucia": {code: "LC"},
      "Saint Martin": {code: "MF"},
      "Saint Pierre and Miquelon": {code: "PM"},
      "Saint Vincent and the Grenadines": {code: "VC"},
      "Sint Maarten": {code: "SX"},
      "South Georgia": {code: "GS"},
      "Suriname": {code: "SR"},
      "Trinidad and Tobago": {code: "TT"},
      "Turks and Caicos Islands": {code: "TC"},
      "United States": {code: "US"},
      "United States Minor Outlying Islands": {code: "UM"},
      "United States Virgin Islands": {code: "VI"},
      "Uruguay": {code: "UY"},
      "Venezuela": {code: "VE"},
      "Albania": {code: "AL"},
      "Andorra": {code: "AD"},
      "Austria": {code: "AT"},
      "Belarus": {code: "BY"},
      "Belgium": {code: "BE"},
      "Bosnia and Herzegovina": {code: "BA"},
      "Bulgaria": {code: "BG"},
      "Croatia": {code: "HR"},
      "Cyprus": {code: "CY"},
      "Czech Republic": {code: "CZ"},
      "Denmark": {code: "DK"},
      "Estonia": {code: "EE"},
      "Faroe Islands": {code: "FO"},
      "Finland": {code: "FI"},
      "France": {code: "FR"},
      "Germany": {code: "DE"},
      "Gibraltar": {code: "GI"},
      "Greece": {code: "GR"},
      "Guernsey": {code: "GG"},
      "Hungary": {code: "HU"},
      "Iceland": {code: "IS"},
      "Ireland": {code: "IE"},
      "Isle of Man": {code: "IM"},
      "Italy": {code: "IT"},
      "Jersey": {code: "JE"},
      "Latvia": {code: "LV"},
      "Liechtenstein": {code: "LI"},
      "Lithuania": {code: "LT"},
      "Luxembourg": {code: "LU"},
      "Macedonia": {code: "MK"},
      "Malta": {code: "MT"},
      "Moldova": {code: "MD"},
      "Monaco": {code: "MC"},
      "Montenegro": {code: "ME"},
      "Netherlands": {code: "NL"},
      "Norway": {code: "NO"},
      "Poland": {code: "PL"},
      "Portugal": {code: "PT"},
      "Romania": {code: "RO"},
      "Russia": {code: "RU"},
      "San Marino": {code: "SM"},
      "Serbia": {code: "RS"},
      "Slovakia": {code: "SK"},
      "Slovenia": {code: "SI"},
      "Spain": {code: "ES"},
      "Svalbard and Jan Mayen": {code: "SJ"},
      "Sweden": {code: "SE"},
      "Switzerland": {code: "CH"},
      "Ukraine": {code: "UA"},
      "United Kingdom": {code: "GB"},
      "Vatican City": {code: "VA"},
      "Åland Islands": {code: "AX"},
    },
    measuresFetched: false
  },
};

// how i fetched this object

// const countryAPI = 'https://restcountries.herokuapp.com/api/v1';
// const proxy1 = 'https://api.codetabs.com/v1/proxy/?quest=';
// const proxy2 = 'https://cors.bridged.cc/';

// const continentsForFetch = [
//   'world',
//   'asia',
//   'europe',
//   'africa',
//   'americas',
// ];

// const state = {
//   continents : {
//     'asia': {
//       countries : {},
//       measuresFetched : false,
//     },
//     'europe': {
//       countries : {},
//       measuresFetched : false,
//     },
//     'africa': {
//       countries : {},
//       measuresFetched : false,
//     },
//     'americas': {
//       countries : {},
//       measuresFetched : false,
//     },
//     'world': {
//       countries : {},
//       measuresFetched : false,
//     },
//   },
// }

// async function fetchContinentCountries(){
//   try{
//     for (let i = 0; i < continentsForFetch.length; i++){
//       let request = (continentsForFetch[i] === 'world')?
//         `${proxy2}${countryAPI}/` :
//         `${proxy2}${countryAPI}/region/${continentsForFetch[i]}`;
//       const fetchRes = await fetch(request);
//       const countriesArr = await fetchRes.json();
//       storeCountries(continentsForFetch[i], countriesArr)
//     }
//     delete state.continents.europe.countries['Kosovo'];
//     delete state.continents.world.countries['Kosovo'];
  
//   // display continents
//   document.querySelector('.continents').style.visibility = 'visible';
//   }  catch (err) {
//     console.log(err);
//   }
// }
// function storeCountries(continent, countriesArr){
//   for (let i = 0; i < countriesArr.length; i++){
//     let countryName = countriesArr[i].name.common;
//     let countryCode = countriesArr[i].cca2;
//     state.continents[continent].countries[countryName] = {};
//     state.continents[continent].countries[countryName]['code'] = countryCode;
//   }
// }

// fetchContinentCountries();
